import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Power Todo App",
  description: "Generated by Caio Melo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#a2b1cf]">{children}</body>
    </html>
  );
}
